name: Deploy PHP to IIS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner for IIS deployment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'  # Specify your PHP version
          extensions: mbstring, mysqli, intl

    

      
      - name: Deploy to IIS
        run: |
          # Adjust the destination path as needed
          $sourcePath = "$env:GITHUB_WORKSPACE\*"
          $destinationPath = "C:\inetpub\wwwroot"  # IIS web root

          Write-Host "Source Path: $sourcePath"
          Write-Host "Destination Path: $destinationPath"

          # Ensure destination path exists
          if (!(Test-Path -Path $destinationPath)) {
            New-Item -Path $destinationPath -ItemType Directory
          }

          # Copy files to IIS web root
          Copy-Item -Path $sourcePath -Destination $destinationPath -Recurse -Force

          # List files in destination to verify
          Get-ChildItem -Path $destinationPath