name: Test and Deploy PHP to IIS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # This is for testing on a Linux runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'
          extensions: mbstring, mysqli, intl

      - name: Run PHP linting
        run: php -l index.php

      - name: Run PHPUnit tests
        run: |
          ./vendor/bin/phpunit --verbose --configuration phpunit.xml.dist

  deploy:
    needs: test
    runs-on: windows-latest  # Change to Windows runner for IIS deployment
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to IIS
        run: |
          Copy-Item -Path "$env:GITHUB_WORKSPACE\*" -Destination "C:\www\" -Recurse -Force
