name: CI/CD - Deploy to IIS

on:
  push:
    branches:
      - main  # Change this to your desired branch

jobs:
  deploy:
    runs-on: windows-latest  # Use a Windows runner

    steps:
      # Step 1: Checkout the latest code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Deploy to IIS
      - name: Deploy to IIS
        run: |
          $ErrorActionPreference = "Stop"

          # Define your variables
          $sourcePath = "$env:GITHUB_WORKSPACE\src"
          $destinationPath = "C:\inetpub\wwwroot\CICDTest"
          $computerName = "${{secrets.IIS_COMPUTERNAME}}"
          $username = "${{ secrets.IIS_USERNAME }}"
          $password = "${{ secrets.IIS_PASSWORD }}"

          # Copy files to IIS
          $securePassword = ConvertTo-SecureString $password -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $securePassword)

          # Use PowerShell to copy files
          Invoke-Command -ComputerName $computerName -Credential $credential -ScriptBlock {
            param ($source, $destination, $creds)
            Copy-Item -Path $source -Destination $destination -Recurse -Force -Credential $creds
          } -ArgumentList $sourcePath, $destinationPath, $credential

      # Optional: Restart IIS after deployment
      - name: Restart IIS
        run: |
          Invoke-Command -ComputerName $computerName -Credential $credential -ScriptBlock {
              iisreset
          }
